@startuml
title Registrace Uživatele

start
:Uživatel otevře registrační stránku;

repeat
  :Vyplní všechny povinné údaje;

  if (Všechna povinná pole vyplněna?) then (ano)
    if (Souhlas se zpracováním osobních údajů?) then (ano)
      :Odeslání registračního formuláře;
      :Validace vstupních dat;

      if (Data jsou platná?) then (ano)
        :Vytvoření uživatelského účtu;
        :Přiřazení role "registered";
        :Automatické přihlášení uživatele;
        :Přesměrování na domovskou stránku;
        stop
      else (ne)
        :Zobrazení chybových hlášek;
      endif
    else (ne)
      :Zobrazení chyby - souhlas je vyžadován;
    endif
  else (ne)
    :Zobrazení chyby - vyplňte všechna pole;
  endif

backward: Návrat na registrační formulář;
@enduml
