@startuml
title Registrace Uživatele

start

:Uživatel otevře registrační stránku;
:Vyplní jméno;
:Vyplní email;
:Vyplní heslo;

if (Souhlas se zpracováním osobních údajů?) then (ano)
  :Odeslání registračního formuláře;
else (ne)
  :Zobrazení chyby - souhlas je vyžadován;
  stop
endif

:Validace vstupních dat;

if (Data jsou platná?) then (ano)
  :Vytvoření uživatelského účtu;
  :Přiřazení role "User";
  :Automatické přihlášení;
  :Zobrazení domovské stránky;
else (ne)
  :Zobrazení chybových hlášek;
  :Návrat na registrační formulář;
endif

stop
@enduml
